name: Aprendendo gitHub Actions 
on:
  schedule:
    - cron: '46 20 * * 5'  # Sexta-feira às 23:36 UTC (20:36 no Brasil)
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
     
          