name: Aprendendo gitHub Actions 
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Run Cypress tests
        run: npx cypress run --e2e
        with:
          component: true