name: Aprendendo gitHub Actions 
on:
  push:
  schedule:
    - cron: '23 14 * * 4'
    - cron: '23 14 * * 6' 
    - cron: '23 14 * * 5' 
    - cron: '23 14 * * 4' 
    - cron: '23 14 * * 3'   
    - cron: '23 14 * * 2' 
    - cron: '23 14 * * 1' 
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
      
     
        