name: Aprendendo gitHub Actions 
on: push
schedule:
    - cron: '0 14 * * 1'  # Executa toda segunda-feira às 11:00 UTC
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true